### ISSUE TITLE
Whitelist Error

### ISSUE THREAD

**Issue by TerrorSoul** [k8thekat/Gatekeeper#5]
I'm trying to run the bot but I'm now getting this error:

![image](https://user-images.githubusercontent.com/27287016/156840441-851f1af0-7ce9-4a75-a3e3-6fba2135d2bc.png)

**Comment by k8thekat** [comment]
Okay, I will look into this. Thanks. Try restarting the bot in the mean time.

**Comment by k8thekat** [comment]
Could you please update your Python Version to 3.7 or greater. Thank you!

**Comment by k8thekat** [comment]
Closing Ticket as I have confirmed it was an older version of Python (pre 3.7)
