### ISSUE TITLE
Chat not reading from in game to Discord.

### ISSUE THREAD

**Issue by Electrofried** [k8thekat/Gatekeeper#6]
**Describe the bug**
I have set up the bot and am having some issues.
The main one is that the bot does not seem to be parsing the console chat and forwarding it to Discord.
I have chat going from discord->minecraft. Just not the other way.

**To Reproduce**
I simply set up the bot following the instructions, added the correct channels with //server (name) channel chat (ID)
Unfortunately nothing is coming to discord.
**Log file** - snippets of the log work.
 
https://gist.github.com/Electrofried/b87677f3c975af4bbdba93fe00274359

**Version** - Look for "Version: alpha-X.X.X"
 -3.0.18

**Comment by k8thekat** [comment]
Hey, thanks for creating an issue. I actually stopped developing this version and put all my efforts into version 2.

While this doesn't immediately solve your problem, I am currently focusing all efforts on Gatekeeper2. 
My apologies.
